export const LOAD_ALL_CONTACTS = 'LOAD_ALL_CONTACTS'
export const ADD_NEW_CONTACTS = 'ADD_NEW_CONTACTS'
export const DELETE_CONTACTS = 'DELETE_CONTACTS'
export const SELECT_A_CONTACT = 'SELECT_A_CONTACT'